#!/bin/sh

# ssh
pkill ssh-agent
eval $(ssh-agent -s)

# Necessary to make chrome pick up the proxy settings stored in gconf.
export DESKTOP_SESSION=gnome # gnome for trusty.

# NOTE: This may break your compose key.
# See http://g/i3-users/YBexXGbik7E for more details.
export GTK_IM_MODULE=xim

# Desktop background color.
xsetroot -solid "#333333"

## Uncomment if you use urxvt terminal emulator.
## Start urxvtd
#urxvtd -q -f -o
#export TERMINAL=urxvtc


# load Xresources
xrdb -merge ~/.Xresources

# HiDPI settings for GTK3+ applications
export GDK_SCALE=1.3
export GDK_DPI_SCALE=1.3

# HiDPI settings for QT applications
export QT_AUTO_SCREEN_SCALE_FACTOR=1

# increase rate of key repeat
xset r rate 300 30

# Comment out the following if this is .xsessionrc file,
# as opposed to .xsession. See https://wiki.debian.org/Xsession for details.
while true; do
    # Log errors to a file (optional but helpful)
    dwm 2> ~/.dwm.log
done
